const ROOT_URL = "https://web3radio-v2.vercel.app";

export const minikitConfig = {
    accountAssociation: {
        "header": "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4Qzc4NTFhRUEwNjYyRjJGY2NFMzhiOTBGOUEzNTI2NGI1RDZmNDIyNTki",
        "payload": "eyJkb21haW4iOiJ3ZWIzcmFkaW8tdjIudmVyY2VsLmFwcCJ9",
        "signature": "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAXdpc-Dl3-llLG2l1ehOsehd5HkQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAPhSELIcxQMC9He6VmhtIBncm2etAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBQNJ7kq0m34SXFVxkqW6SvXWyC5WG4bHLEifamCQ6M2MXpMT7qXBeOFWi_QOzLA7m0cBuNDbk7ZJoDd88Wpb9BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI"
    },
    miniapp: {
        version: "1",
        name: "Web3Radio",
        subtitle: "Decentralized Radio Station",
        description: "Listen to your favorite web3 radio stations",
        screenshotUrls: [`${ROOT_URL}/assets/web3radio-logo.png`],
        iconUrl: `${ROOT_URL}/assets/web3radio-logo.png`,
        splashImageUrl: `${ROOT_URL}/assets/web3radio-logo.png`,
        splashBackgroundColor: "#000000",
        homeUrl: ROOT_URL,
        webhookUrl: `${ROOT_URL}/api/webhook`,
        primaryCategory: "social",
        tags: ["music", "radio", "web3"],
        heroImageUrl: `${ROOT_URL}/assets/web3radio-logo.png`,
        tagline: "The Future of Radio",
        ogTitle: "Web3Radio",
        ogDescription: "Decentralized Radio Station",
        ogImageUrl: `${ROOT_URL}/assets/web3radio-logo.png`,
    },
} as const;
