-- Insert sample crypto/web3 events (offline and online)
INSERT INTO public.events (title, date, location, description, image_url) VALUES
('Web3 Jakarta Summit 2025', '2025-08-15', 'Jakarta Convention Center', 'Join leading Web3 builders, investors, and developers for Indonesia''s premier blockchain conference. Learn about DeFi, NFTs, and the future of decentralized internet.', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400'),
('DeFi Developer Workshop', '2025-08-22', 'Online - Zoom', 'Hands-on workshop for building DeFi applications on Base network. Learn smart contract development, yield farming protocols, and liquidity pools.', 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400'),
('NFT Art Exhibition: Digital Renaissance', '2025-09-01', 'Museum Nasional, Jakarta', 'Explore the intersection of traditional art and blockchain technology. Featuring works from Indonesian NFT artists and interactive blockchain demos.', 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=400'),
('Base Network Developers Meetup', '2025-09-08', 'Online - Discord', 'Monthly meetup for Base developers. Discuss latest updates, share projects, and collaborate on building the future of Layer 2 solutions.', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400'),
('Crypto Trading Masterclass', '2025-09-15', 'Kuningan City Mall, Jakarta', 'Learn advanced trading strategies, technical analysis, and risk management from professional crypto traders. Suitable for intermediate to advanced traders.', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400'),
('Web3 Radio Live: ETH Global Afterparty', '2025-09-20', 'Online - Web3 Radio Studio', 'Live broadcast event featuring interviews with ETH Global winners, discussions about winning projects, and music from crypto artists.', 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400'),
('Blockchain for Social Good Conference', '2025-10-01', 'Universitas Indonesia, Depok', 'Exploring how blockchain technology can solve real-world problems in healthcare, education, and social welfare. Student-friendly pricing available.', 'https://images.unsplash.com/photo-1559223607-a43c990c692c?w=400'),
('Web3 Radio Schedule: Morning Crypto News', '2025-08-01', 'Web3 Radio Studio', 'Daily broadcast: 07:00-09:00 WIB - Latest crypto market updates, regulatory news, and interviews with industry leaders.', 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=400'),
('Web3 Radio Schedule: DeFi Deep Dive', '2025-08-01', 'Web3 Radio Studio', 'Weekly show: Every Wednesday 20:00-21:00 WIB - In-depth analysis of DeFi protocols, yield farming strategies, and market trends.', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400'),
('Web3 Radio Schedule: NFT Spotlight', '2025-08-01', 'Web3 Radio Studio', 'Weekly show: Every Friday 19:00-20:00 WIB - Featuring NFT artists, collection reviews, and marketplace updates.', 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=400');

-- Insert sample crypto/web3 news articles
INSERT INTO public.news (title, content, date, image_url) VALUES
('Base Network Sees Record Breaking TVL Growth', 'Coinbase''s Layer 2 solution Base has reached a new all-time high in Total Value Locked (TVL), surpassing $3 billion. The growth is attributed to increased DeFi adoption and the launch of several high-profile projects including Aerodrome and Uniswap V3. Base continues to offer low transaction fees and fast settlement times, making it attractive for both developers and users seeking efficient blockchain interactions.', '2025-07-28', 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400'),
('Indonesia Announces New Crypto Regulations', 'The Indonesian government has released updated guidelines for cryptocurrency trading and taxation. The new regulations provide clearer frameworks for crypto exchanges, DeFi protocols, and NFT marketplaces. Finance Minister Sri Mulyani stated that these regulations aim to protect investors while fostering innovation in the digital asset space. Crypto exchanges now have 6 months to comply with the new requirements.', '2025-07-27', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400'),
('Major DeFi Protocol Launches on Base', 'Compound Finance, one of the largest DeFi lending protocols, has officially launched on Base network. Users can now lend and borrow assets with significantly lower gas fees compared to Ethereum mainnet. The launch includes support for major cryptocurrencies including ETH, USDC, and newly added support for Indonesian Rupiah stablecoin (IDRT). Early adopters can earn additional rewards through the Base ecosystem incentive program.', '2025-07-26', 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400'),
('NFT Market Shows Signs of Recovery', 'The NFT market has shown promising signs of recovery with trading volume increasing by 45% over the past month. Indonesian NFT artists are gaining international recognition, with several collections selling out on major platforms. The trend is driven by utility-focused NFTs and real-world asset tokenization. Experts predict continued growth as brands explore NFT integration for customer engagement and loyalty programs.', '2025-07-25', 'https://images.unsplash.com/photo-1618005198919-d3d4b5a92ead?w=400'),
('Web3 Social Media Platform Gains Traction', 'Decentralized social media platform Lens Protocol has reached 100,000 active users, with a significant portion coming from Southeast Asian markets. The platform allows users to own their social graph and monetize content directly. Indonesian creators are embracing the platform for its creator-friendly economics and resistance to censorship. Integration with major wallets makes onboarding easier for new users.', '2025-07-24', 'https://images.unsplash.com/photo-1611095973362-a1b5f5a9b8a3?w=400'),
('Central Bank Digital Currency Pilot Program', 'Bank Indonesia announces the pilot program for its Central Bank Digital Currency (CBDC) scheduled to begin in Q4 2025. The digital rupiah will be tested with select financial institutions and merchants across Jakarta and Surabaya. The CBDC aims to improve financial inclusion and reduce transaction costs while maintaining monetary policy effectiveness. Privacy and security features are being developed in collaboration with local fintech companies.', '2025-07-23', 'https://images.unsplash.com/photo-1560472354-6056e8f6d1b8?w=400');