create table public.pages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  content text,
  is_published boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
